### ISSUE TITLE
这个版本支持的GAE版本是什么？

### ISSUE THREAD

**Issue by DrayChou** [lilydjwg/gaetalk#1]
是 GAE 的 High Replication？
还是之前的版本？

**Comment by lilydjwg** [comment]
看开发的日期就知道是之前的 Python 2.5 版本啦。High Replication 有什么区别吗？

另外注意下，由于 GAE 收费政策调整，此项目已经不再开发。（本来是想在 README 里放个通知的，懒得重新克隆，github 的在线编辑器又不安全又不好用，就放弃了。）

**Comment by DrayChou** [comment]
High Replication 版本里有些配置什么的变掉了，具体不清楚。我上传了你的项目，在原版和新版下面都不能正常工作。
那你这个项目就这样 OVER 啦？

有没有推荐可以用的gtalk bot 啊？

在 2012年6月26日 上午1:39，依云 <
reply@reply.github.com

**Comment by lilydjwg** [comment]
原版应该能够工作的呀，我这里还留着个可用的群呢。你看看日志？

如果你有 Linux/FreeBSD 的服务器的话，可以用 [xmpptalk](https://github.com/lilydjwg/xmpptalk) 的。不过它目前的版本部署起来有点麻烦。

**Comment by DrayChou** [comment]
Check out 威 's photos on Facebook.

If you sign up for Facebook, you'll be able to stay connected with friends by seeing their photos and videos, staying up to date with their latest status updates, exchanging messages and more.

快到 Facebook 来找威吧！
http://www.facebook.com/p.php?i=100001365023691&k=AQD1utaoamNLR2c1tuVsdk6t40czqv_bnElUK5PiAtDaE00H6h-pHXYLxD1GhWG29eLF1QiUEEXkqH56TFbEtEYm1iA&r&app_id=350685531728

已有帐户？请将该邮件地址关联到你的帐户：
http://www.facebook.com/merge_accounts.php?e=reply%2Bi-5254544-c2711e9ed5aee136ab2c3e8a121d7c026de6fd3a-760245%40reply.github.com&c=AQBur4Ru5QU4iAFvUwgOKlMIMZJhlMbUThcW4448q-n28w

# 

此消息已发送到 reply@reply.github.com 如果伱不希望收到这些电子邮件从Facebook，请点击以下链接退订。
http://www.facebook.com/o.php?k=AS2njf-g6hUmFe8g&e=reply%2Bi-5254544-c2711e9ed5aee136ab2c3e8a121d7c026de6fd3a-760245%40reply.github.com&mid=HMTA3OTU0MjIxOnJlcGx5K2ktNTI1NDU0NC1jMjcxMWU5ZWQ1YWVlMTM2YWIyYzNlOGExMjFkN2MwMjZkZTZmZDNhLTc2MDI0NUByZXBseS5naXRodWIuY29tOjg
 Facebook, Inc. Attention: Department 415 P.O Box 10005 Palo Alto CA 94303

**Comment by DrayChou** [comment]
Check out 威 's photos on Facebook.

If you sign up for Facebook, you'll be able to stay connected with friends by seeing their photos and videos, staying up to date with their latest status updates, exchanging messages and more.

快到 Facebook 来找威吧！
http://www.facebook.com/p.php?i=100001365023691&k=AQC5QcZfGK2nP5Q_nNXCJwSErm7rHWOgFwV0q5aukbmDntbCR-as4WMZG4_JN4_xlGPfUaOy0fTj45oq5BpmxAsfits&r&app_id=350685531728

已有帐户？请将该邮件地址关联到你的帐户：
http://www.facebook.com/merge_accounts.php?e=reply%2Bi-5254544-c2711e9ed5aee136ab2c3e8a121d7c026de6fd3a-760245%40reply.github.com&c=AQBur4Ru5QU4iAFvUwgOKlMIMZJhlMbUThcW4448q-n28w&source=unknown

# 

此消息已发送到 reply@reply.github.com 如果伱不希望收到这些电子邮件从Facebook，请点击以下链接退订。
http://www.facebook.com/o.php?k=AS2njf-g6hUmFe8g&e=reply%2Bi-5254544-c2711e9ed5aee136ab2c3e8a121d7c026de6fd3a-760245%40reply.github.com&mid=HMTEwMDM3MjI0OnJlcGx5K2ktNTI1NDU0NC1jMjcxMWU5ZWQ1YWVlMTM2YWIyYzNlOGExMjFkN2MwMjZkZTZmZDNhLTc2MDI0NUByZXBseS5naXRodWIuY29tOjg
 Facebook, Inc. Attention: Department 415 P.O Box 10005 Palo Alto CA 94303
